version: '3.4'

services:
  identifier:
    restart: no
  virtuoso:
    ports:
      - "8890:8890"
    restart: no
  mocklogin:
    image: lblod/mock-login-service:latest
    links:
      - database:database
    restart: no
